Upgrading the kernel to 5.4.26 with web10g. Upgraded base to Ubuntu Bionic (18.04) Added dublin tarceroute to packages - not yet incorporated into tests Has to stop using Net::SSH2 for file transfer as it's not working at the moment. Falling back to scp. Which means I had to include the openssh-client package Have not yet really started trying to cut down on the total size yet

diff --git a/isosource/chroot/sbin/dhclient-script b/isosource/chroot/sbin/dhclient-script
--- a/isosource/chroot/sbin/dhclient-script
+++ b/isosource/chroot/sbin/dhclient-script
@@ -24,6 +24,9 @@ export BASH_XTRACEFD=
 
 # The alias handling in here probably still sucks. -mdz
 
+# log an error.
+error() { logger -p daemon.err "$@"; }
+
 # wait for given file to be writable
 wait_for_rw() {
     local file=$1
@@ -133,31 +136,64 @@ make_resolv_conf() {
 
 # set host name
 set_hostname() {
-    local current_hostname
-
     if [ -n "$new_host_name" ]; then
-        current_hostname=$(hostname)
+        local current_hostname=$(hostname)
 
         # current host name is empty, '(none)' or 'localhost' or differs from new one from DHCP
         if [ -z "$current_hostname" ] ||
            [ "$current_hostname" = '(none)' ] ||
            [ "$current_hostname" = 'localhost' ] ||
            [ "$current_hostname" = "$old_host_name" ]; then
-           if [ "$new_host_name" != "$old_host_name" ]; then
+           if [ "$new_host_name" != "$current_host_name" ]; then
                hostname "$new_host_name"
            fi
         fi
     fi
 }
 
+# set the link up and wait for ipv6 link local dad to finish
+ipv6_link_up_and_dad() {
+    local dev=$1 delay=${2:-0.1} attempts=${3:-60}
+    ip link set up dev "$dev" ||
+        { error "$dev: failed to set link up"; return 1; }
+    local n=0
+    while :; do
+        n=$((n+1))
+        # note: busybox ip does not understand 'tentative' as input
+        # so we cannot just use the tentative flag and check for empty
+        out=$(ip -6 -o address show dev "$dev" scope link) || {
+            error "$dev: checking for link-local addresses failed";
+            return 1
+        }
+        # another note: the output may be empty if the link local tentative addr
+        # isn't up just yet, so we need to make sure there is at least one 'inet6'
+        # match before returning success.  We need to keep checking for both
+        # 'tentative' case and default (no inet6 address) case. (LP: #1718568)
+        # Don't reorder tentative/inet6 - we need to check for tentative first.
+        case " $out " in
+            *\ dadfailed\ *)
+                error "$dev: ipv6 dad failed."
+                return 1;;
+            *\ tentative\ *) :;;
+            *\ inet6\ *) return 0;;
+            *) :;;
+        esac
+        [ $n -lt $attempts ] || {
+            error "$dev: time out waiting for permanent link-local address"
+            return 1;
+        }
+        sleep $delay
+    done
+}
+
 # run given script
 run_hook() {
-    local script
-    local exit_status
-    script="$1"
+    local script="$1"
+    local exit_status=0
 
     if [ -f $script ]; then
         . $script
+        exit_status=$?
     fi
 
     if [ -n "$exit_status" ] && [ "$exit_status" -ne 0 ]; then
@@ -169,14 +205,13 @@ run_hook() {
 
 # run scripts in given directory
 run_hookdir() {
-    local dir
-    local exit_status
-    dir="$1"
+    local dir="$1"
+    local exit_status=0
 
     if [ -d "$dir" ]; then
         for script in $(run-parts --list $dir); do
-            run_hook $script || true
-            exit_status=$?
+            run_hook $script
+            exit_status=$((exit_status|$?))
         done
     fi
 
@@ -185,7 +220,7 @@ run_hookdir() {
 
 # Must be used on exit.   Invokes the local dhcp client exit hooks, if any.
 exit_with_hooks() {
-    exit_status=$1
+    local exit_status=$1
 
     # Source the documented exit-hook script, if it exists
     if ! run_hook /etc/dhcp/dhclient-exit-hooks; then
@@ -390,7 +425,7 @@ case "$reason" in
 
     PREINIT6)
         # ensure interface is up
-        ip link set ${interface} up
+        ipv6_link_up_and_dad "$interface"
 
         # flush any stale global permanent IPs from interface
         ip -6 addr flush dev ${interface} scope global permanent
@@ -398,9 +433,9 @@ case "$reason" in
         ;;
 
     BOUND6|RENEW6|REBIND6)
-        if [ "${new_ip6_address}" ] && [ "${new_ip6_prefixlen}" ]; then
+        if [ "${new_ip6_address}" ]; then
             # set leased IP
-            ip -6 addr add ${new_ip6_address}/${new_ip6_prefixlen} \
+            ip -6 addr add ${new_ip6_address} \
                 dev ${interface} scope global
         fi
 
@@ -414,23 +449,19 @@ case "$reason" in
         ;;
 
     DEPREF6)
-        if [ -z "${cur_ip6_prefixlen}" ]; then
-            exit_with_hooks 2
-        fi
-
         # set preferred lifetime of leased IP to 0
-        ip -6 addr change ${cur_ip6_address}/${cur_ip6_prefixlen} \
+        ip -6 addr change ${cur_ip6_address} \
             dev ${interface} scope global preferred_lft 0
 
         ;;
 
     EXPIRE6|RELEASE6|STOP6)
-        if [ -z "${old_ip6_address}" ] || [ -z "${old_ip6_prefixlen}" ]; then
+        if [ -z "${old_ip6_address}" ]; then
             exit_with_hooks 2
         fi
 
         # delete leased IP
-        ip -6 addr del ${old_ip6_address}/${old_ip6_prefixlen} \
+        ip -6 addr del ${old_ip6_address} \
             dev ${interface}
 
         ;;
diff --git a/isosource/chroot/usr/bin/encfssh b/isosource/chroot/usr/bin/encfssh
--- a/isosource/chroot/usr/bin/encfssh
+++ b/isosource/chroot/usr/bin/encfssh
@@ -2,20 +2,21 @@
 
 # This script mounts an encfs filesystem, starts a shell in the mounted
 # directory, and then unmounts the filesystem when the shell exits.
-# This is an equivalent of the cfssh utility for cfs. 
+# This is an equivalent of the cfssh utility for cfs.
 # Contributed by David Rosenstrauch.
 
 canonicalize() {
-	cd "$1"
+	cd "$1" || return
 	pwd
 }
 
 
-if [ -z "$1" -o "$1" = "-h" ]; then
-	echo Usage: encfssh encrypted_directory [unencrypted-directory [-p]]
+case $1 in "" | -h | --help)
+	echo "Usage: encfssh encrypted_directory [unencrypted-directory [-p]]"
 	echo "  -p   mount the unencrypted directory as public"
 	exit 1
-fi
+	;;
+esac
 
 enc_dir=$1
 unenc_dir_given=false
@@ -28,40 +29,65 @@ if [ ! -z "$2" ]; then
 	    mount_public=true
 	fi
     done
+    [ -d "$unenc_dir" ] || mkdir -- "$unenc_dir"
 else
-    unenc_dir="$(mktemp -d)"
+    unenc_dir=$(mktemp -d .XXXXXXXX)
 fi
 
 if [ ! -d "$enc_dir" ]; then
-    mkdir $enc_dir
-fi
-if [ ! -d "$unenc_dir" ]; then
-    mkdir $unenc_dir
+    mkdir -- "$enc_dir"
 fi
 
 enc_dir=$(canonicalize "$enc_dir")
 unenc_dir=$(canonicalize "$unenc_dir")
 
-options=""
-if $unenc_dir_given; then
-    if $mount_public; then
+options=
+if [ "$unenc_dir_given" = "true" ]; then
+    if [ "$mount_public" = "true" ]; then
 	options="-- -o allow_other"
     fi
 fi
 
 # Attach the directory and change into it
-if encfs $enc_dir $unenc_dir $options; then :; else
+
+## options can only have one of two values (empty, or "-- -o allow_other"), so
+## this unquoted expansion is safe; disabling relevant shellcheck warning.
+## See code review feedback requesting this attached to
+## https://github.com/vgough/encfs/pull/258/files/09b9fc5efb7c2694976baffe7dd21172fd182027
+## ...and that warning's explanation at https://github.com/koalaman/shellcheck/wiki/SC2086
+# shellcheck disable=SC2086
+if encfs "$enc_dir" "$unenc_dir" $options; then :; else
     echo "encfs failed"
-    rmdir $unenc_dir
+    rmdir -- "$unenc_dir"
     exit 1
 fi
-if ! $unenc_dir_given; then
-    chmod 700 $unenc_dir
+if ! [ "$unenc_dir_given" = "true" ]; then
+    chmod 700 "$unenc_dir"
 fi
-echo "Directory is $unenc_dir"
-orig_dir=$(pwd)
-cd $unenc_dir
+echo "Directory is $unenc_dir" >&2
+cd "$unenc_dir" || exit
 
-# Set the shell up
-exec /bin/sh -c "$SHELL ; cd $orig_dir ; fusermount -u $unenc_dir ; if ! $unenc_dir_given; then rmdir $unenc_dir; fi"
+# Fall back to umount if fusermount is not available (e.g., on OS X)
+fuse_umount() {
+	if command -v fusermount >/dev/null 2>&1; then
+		fusermount -u "$@"
+	else
+		umount "$@" # MacOS case
+	fi
+}
 
+# Honor the SHELL environment variable to select a shell to run
+"$SHELL"; retval=$?
+
+# ensure that this shell isn't itself holding the mounted directory open
+# ...but avoid terminating on failure, *or* causing a shellcheck warning for
+#    failing to check exit status from cd.
+cd / ||:
+
+# if unmount fails, skip rmdir, always use exit status of failure
+fuse_umount "$unenc_dir" || exit
+
+if ! [ "$unenc_dir_given" = true ]; then
+	rmdir -- "$unenc_dir"
+fi
+exit "$retval"
diff --git a/isosource/chroot/usr/sbin/mkinitramfs b/isosource/chroot/usr/sbin/mkinitramfs
--- a/isosource/chroot/usr/sbin/mkinitramfs
+++ b/isosource/chroot/usr/sbin/mkinitramfs
@@ -7,8 +7,8 @@ export PATH='/usr/bin:/sbin:/bin'
 keep="n"
 CONFDIR="/etc/initramfs-tools"
 verbose="n"
-test -e /bin/busybox && BUSYBOXDIR=/bin
-test -e /usr/lib/initramfs-tools/bin/busybox && BUSYBOXDIR=/usr/lib/initramfs-tools/bin
+# Will be updated by busybox's conf hook, if present
+BUSYBOXDIR=
 export BUSYBOXDIR
 
 OPTIONS=`getopt -o c:d:ko:r:v -n "$0" -- "$@"`
@@ -72,7 +72,9 @@ done
 # FIXME: deprecated those settings on mkinitramfs run
 # 	 these conf dirs are for boot scripts and land on initramfs
 for i in ${EXTRA_CONF}; do
-	if [ -e  ${CONFDIR}/conf.d/${i} ]; then
+	if [ -d  ${CONFDIR}/conf.d/${i} ]; then
+		echo "Warning: ${CONFDIR}/conf.d/${i} is a directory instead of file, ignoring."
+	elif [ -e  ${CONFDIR}/conf.d/${i} ]; then
 		. ${CONFDIR}/conf.d/${i}
 	elif [ -e  /usr/share/initramfs-tools/conf.d/${i} ]; then
 		. /usr/share/initramfs-tools/conf.d/${i}
@@ -81,10 +83,18 @@ done
 
 # source package confs
 for i in /usr/share/initramfs-tools/conf-hooks.d/*; do
-	if [ -e "${i}" ]; then
+	if [ -d "${i}" ]; then
+		echo "Warning: ${i} is a directory instead of file, ignoring."
+	elif [ -e "${i}" ]; then
 		. "${i}"
 	fi
 done
+
+# Check busybox dependency
+if [ "${BUSYBOX}" = "y" ] && [ -z "${BUSYBOXDIR}" ]; then
+	echo >&2 "E: busybox-initramfs, version 1:1.22.0-17~ or later, is required but not installed"
+	exit 1
+fi
 
 if [ -n "${UMASK:-}" ]; then
 	umask "${UMASK}"
@@ -104,12 +114,6 @@ if [ ${#} -ne 1 ]; then
 else
 	version="${1}"
 fi
-
-# Check that we're using a new enough kernel version, first for ourselves,
-# then for each of the hooks, which can have a MINKVER variable defined
-check_minkver ${version}
-check_minkver ${version} /usr/share/initramfs-tools/hooks
-check_minkver ${version} ${CONFDIR}/hooks
 
 case "${version}" in
 /lib/modules/*/[!/]*)
@@ -141,14 +145,14 @@ if ! command -v "${compress}" >/dev/null 2>&1; then
 	COMPRESS=gzip
 fi
 
-if ! `grep -q -i ^config_rd_${COMPRESS%p} /boot/config-${version}` ; then
+if dpkg --compare-versions "${version}" lt "2.6.38" 2>/dev/null; then
 	compress=gzip
 	[ "${verbose}" = y ] && \
-		echo "linux-2.6 misses ${COMPRESS} support, using gzip"
+		echo "linux-2.6 likely misses ${COMPRESS} support, using gzip"
 fi
 
 [ "${compress}" = lzop ] && compress="lzop -9"
-[ "${compress}" = xz ] && compress="xz -8 --check=crc32"
+[ "${compress}" = xz ] && compress="xz --check=crc32"
 
 if [ -d "${outfile}" ]; then
 	echo "${outfile} is a directory" >&2
@@ -159,23 +163,33 @@ MODULESDIR="/lib/modules/${version}"
 
 if [ ! -e "${MODULESDIR}" ]; then
 	echo "WARNING: missing ${MODULESDIR}"
-	echo "Device driver support needs thus be built-in linux image!"
+	echo "Ensure all necessary drivers are built into the linux image!"
 fi
 if [ ! -e "${MODULESDIR}/modules.dep" ]; then
 	depmod ${version}
 fi
 
-DESTDIR="$(mktemp -d ${TMPDIR:-/tmp}/mkinitramfs_XXXXXX)" || exit 1
+# Prepare to clean up temporary files on exit
+DESTDIR=
+__TMPCPIOGZ=
+__TMPEARLYCPIO=
+clean_on_exit() {
+	if [ "${keep}" = "y" ]; then
+		echo "Working files in ${DESTDIR:-<not yet created>}, early initramfs in ${__TMPEARLYCPIO:-<not yet created>} and overlay in ${__TMPCPIOGZ:-<not yet created>}"
+	else
+		for path in "${DESTDIR}" "${__TMPCPIOGZ}" "${__TMPEARLYCPIO}"; do
+			test -z "${path}" || rm -rf "${path}"
+		done
+	fi
+}
+trap clean_on_exit EXIT
+trap "exit 1" INT TERM	# makes the EXIT trap effective even when killed
+
+# Create temporary directory and files for initramfs contents
+[ -n "${TMPDIR}" ] && [ ! -w "${TMPDIR}" ] && unset TMPDIR
+DESTDIR="$(mktemp -d ${TMPDIR:-/var/tmp}/mkinitramfs_XXXXXX)" || exit 1
 chmod 755 "${DESTDIR}"
-
-# do not execute cache_run_scripts() if mounted with noexec
-NOEXEC=""
-fs=$(df -P $DESTDIR | tail -1 | awk '{print $6}')
-if [ -n "$fs" ] && mount | grep -q "on $fs .*noexec" ; then
-	NOEXEC=1
-fi
-
-__TMPCPIOGZ="$(mktemp ${TMPDIR:-/tmp}/mkinitramfs-OL_XXXXXX)" || exit 1
+__TMPCPIOGZ="$(mktemp ${TMPDIR:-/var/tmp}/mkinitramfs-OL_XXXXXX)" || exit 1
 __TMPEARLYCPIO="$(mktemp ${TMPDIR:-/var/tmp}/mkinitramfs-FW_XXXXXX)" || exit 1
 
 DPKG_ARCH=`dpkg --print-architecture`
@@ -191,6 +205,7 @@ export verbose
 export MODULES
 export BUSYBOX
 export COMPCACHE_SIZE
+export RESUME
 
 # Private, used by 'catenate_cpiogz'.
 export __TMPCPIOGZ
@@ -241,7 +256,7 @@ esac
 # Resolve hidden dependencies
 hidden_dep_add_modules
 
-# First file executed by linux-2.6
+# First file executed by linux
 cp -p /usr/share/initramfs-tools/init ${DESTDIR}/init
 
 # add existant boot scripts
@@ -255,11 +270,11 @@ for b in $(cd /usr/share/initramfs-tools/scripts/ && find . \
 	cp -p "/usr/share/initramfs-tools/scripts/${b}" \
 		"${DESTDIR}/scripts/$(dirname "${b}")/"
 done
-for b in $(cd "${CONFDIR}/scripts" && find . \
-	-regextype posix-extended -regex '.*/[[:alnum:]\._-]+$' -type f); do
+# Prune dot-files/directories and limit depth to exclude VCS files
+for b in $(cd "${CONFDIR}/scripts" && find . -maxdepth 2 -name '.?*' -prune -o \
+	-regextype posix-extended -regex '.*/[[:alnum:]\._-]+$' -type f -print); do
 	option=$(sed '/^OPTION=/!d;$d;s/^OPTION=//;s/[[:space:]]*$//' "${CONFDIR}/scripts/${b}")
 	[ -z "${option}" ] || eval test -n \"\${$option}\" -a \"\${$option}\" != \"n\" || continue
-
 	[ -d "${DESTDIR}/scripts/$(dirname "${b}")" ] \
 		|| mkdir -p "${DESTDIR}/scripts/$(dirname "${b}")"
 	cp -p "${CONFDIR}/scripts/${b}" "${DESTDIR}/scripts/$(dirname "${b}")/"
@@ -269,9 +284,10 @@ echo "DPKG_ARCH=${DPKG_ARCH}" > ${DESTDIR}/conf/arch.conf
 cp -p "${CONFDIR}/initramfs.conf" ${DESTDIR}/conf
 for i in ${EXTRA_CONF}; do
 	if [ -e "${CONFDIR}/conf.d/${i}" ]; then
-		copy_exec "${CONFDIR}/conf.d/${i}" /conf/conf.d
+		copy_file config "${CONFDIR}/conf.d/${i}" /conf/conf.d
 	elif [ -e "/usr/share/initramfs-tools/conf.d/${i}" ]; then
-		copy_exec "/usr/share/initramfs-tools/conf.d/${i}" /conf/conf.d
+		copy_file config "/usr/share/initramfs-tools/conf.d/${i}" \
+			/conf/conf.d
 	fi
 done
 
@@ -285,33 +301,38 @@ if ! command -v ldd >/dev/null 2>&1 ; then
 	exit 1
 fi
 
+# fstab and mtab
+touch "${DESTDIR}/etc/fstab"
+ln -s /proc/mounts "${DESTDIR}/etc/mtab"
+
+# install wait-for-root binary.
 copy_exec /usr/lib/initramfs-tools/bin/wait-for-root /sbin
 
 # module-init-tools
 copy_exec /sbin/modprobe /sbin
 copy_exec /sbin/rmmod /sbin
-mkdir -p "${DESTDIR}/etc/modprobe.d"
-cp -a /etc/modprobe.d/* "${DESTDIR}/etc/modprobe.d/"
-
-# util-linux
-copy_exec /sbin/blkid /sbin
+mkdir -p "${DESTDIR}/etc/modprobe.d" "${DESTDIR}/lib/modprobe.d"
+for file in /etc/modprobe.d/*.conf /lib/modprobe.d/*.conf ; do
+	if test -e "$file" || test -L "$file" ; then
+		copy_file config "$file"
+	fi
+done
 
 # workaround: libgcc always needed on old-abi arm
 if [ "$DPKG_ARCH" = arm ] || [ "$DPKG_ARCH" = armeb ]; then
 	cp -a /lib/libgcc_s.so.1 "${DESTDIR}/lib/"
 fi
 
-run_scripts /usr/share/initramfs-tools/hooks optional
-run_scripts "${CONFDIR}"/hooks optional
+run_scripts_optional /usr/share/initramfs-tools/hooks
+run_scripts_optional "${CONFDIR}"/hooks
+
+# Avoid double sleep when using older udev scripts
+sed -i 's/^\s*sleep \$ROOTDELAY$/:/' "${DESTDIR}/scripts/init-top/udev"
 
 # cache boot run order
-if [ -n "$NOEXEC" ]; then
-	echo "W: TMPDIR is mounted noexec, will not cache run scripts."
-else
-	for b in $(cd "${DESTDIR}/scripts" && find . -mindepth 1 -type d); do
-		cache_run_scripts "${DESTDIR}" "/scripts/${b#./}"
-	done
-fi
+for b in $(cd "${DESTDIR}/scripts" && find . -mindepth 1 -type d); do
+	cache_run_scripts "${DESTDIR}" "/scripts/${b#./}"
+done
 
 # generate module deps
 depmod -a -b "${DESTDIR}" ${version}
@@ -326,8 +347,17 @@ fi
 
 # Apply DSDT to initramfs
 if [ -e "${CONFDIR}/DSDT.aml" ]; then
-	copy_exec "${CONFDIR}/DSDT.aml" /
+	copy_file DSDT "${CONFDIR}/DSDT.aml"
 fi
+
+# Make sure there is a final sh in initramfs
+if [ ! -e "${DESTDIR}/bin/sh" ]; then
+	copy_exec /bin/sh "${DESTDIR}/bin/"
+fi
+
+case "${MODULES}" in
+	netboot|most) add_dns "${DESTDIR}/";;
+esac
 
 # Remove any looping or broken symbolic links, since they break cpio.
 [ "${verbose}" = y ] && xargs_verbose="-t"
@@ -356,8 +386,11 @@ else
 fi
 
 (
+# preserve permissions if root builds the image, see #633582
+[ "$(id -ru)" != 0 ] && cpio_owner_root="-R 0:0"
+
 # work around lack of "set -o pipefail" for the following pipe:
-# cd "${DESTDIR}" && find . | cpio --quiet -R 0:0 -o -H newc | gzip >>"${outfile}" || exit 1
+# cd "${DESTDIR}" && find . | cpio --quiet $cpio_owner_root -o -H newc | gzip >>"${outfile}" || exit 1
 exec 3>&1
 eval `
 	# http://cfaj.freeshell.org/shell/cus-faq-2.html
@@ -366,7 +399,7 @@ eval `
 	{
 		find . 4>&-; echo "ec1=$?;" >&4
 	} | {
-		cpio --quiet -R 0:0 -o -H newc 4>&-; echo "ec2=$?;" >&4
+		cpio --quiet $cpio_owner_root -o -H newc 4>&-; echo "ec2=$?;" >&4
 	} | ${compress} >>"${outfile}"
 	echo "ec3=$?;" >&4
 `
@@ -386,14 +419,6 @@ fi
 
 if [ -s "${__TMPCPIOGZ}" ]; then
 	cat "${__TMPCPIOGZ}" >>"${outfile}" || exit 1
-fi
-
-if [ "${keep}" = "y" ]; then
-	echo "Working files in ${DESTDIR}, early initramfs in ${__TMPEARLYCPIO} and overlay in ${__TMPCPIOGZ}"
-else
-	rm -rf "${DESTDIR}"
-	rm -rf "${__TMPCPIOGZ}"
-	rm -rf "${__TMPEARLYCPIO}"
 fi
 
 exit 0
diff --git a/isosource/chroot/usr/share/initramfs-tools/init b/isosource/chroot/usr/share/initramfs-tools/init
--- a/isosource/chroot/usr/share/initramfs-tools/init
+++ b/isosource/chroot/usr/share/initramfs-tools/init
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+# Default PATH differs between shells, and is not automatically exported
+# by klibc dash.  Make it consistent.
+export PATH=/sbin:/usr/sbin:/bin:/usr/bin
+
 [ -d /dev ] || mkdir -m 0755 /dev
 [ -d /root ] || mkdir -m 0700 /root
 [ -d /sys ] || mkdir /sys
@@ -8,25 +12,25 @@
 mkdir -p /var/lock
 mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
 mount -t proc -o nodev,noexec,nosuid proc /proc
-# Some things don't work properly without /etc/mtab.
-ln -sf /proc/mounts /etc/mtab
 
-grep -q '\<quiet\>' /proc/cmdline || echo "Loading, please wait..."
+case " $(cat /proc/cmdline) " in
+*\ quiet\ *)
+	quiet=y
+	;;
+*)
+	quiet=n
+	echo "Loading, please wait..."
+	;;
+esac
+export quiet
 
 # Note that this only becomes /dev on the real filesystem if udev's scripts
 # are used; which they will be, but it's worth pointing out
-if ! mount -t devtmpfs -o mode=0755 udev /dev; then
-	echo "W: devtmpfs not available, falling back to tmpfs for /dev"
-	mount -t tmpfs -o mode=0755 udev /dev
-	[ -e /dev/console ] || mknod -m 0600 /dev/console c 5 1
-	[ -e /dev/null ] || mknod /dev/null c 1 3
-fi
+mount -t devtmpfs -o nosuid,mode=0755 udev /dev
 mkdir /dev/pts
 mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts || true
 mount -t tmpfs -o "noexec,nosuid,size=10%,mode=0755" tmpfs /run
-mkdir /run/initramfs
-# compatibility symlink for the pre-oneiric locations
-ln -s /run/initramfs /dev/.initramfs
+mkdir -m 0755 /run/initramfs
 
 # Export the dpkg architecture
 export DPKG_ARCH=
@@ -41,12 +45,12 @@ export ROOTDELAY=
 export ROOTFLAGS=
 export ROOTFSTYPE=
 export IP=
+export IP6=
 export BOOT=
 export BOOTIF=
 export UBIMTD=
 export break=
 export init=/sbin/init
-export quiet=n
 export readonly=y
 export rootmnt=/root
 export debug=
@@ -54,11 +58,17 @@ export panic=
 export blacklist=
 export resume=
 export resume_offset=
+export drop_caps=
+export fastboot=n
+export forcefsck=n
+export fsckfix=
 export recovery=
+export NETWORK_SKIP_ENSLAVED=
+
 
 # mdadm needs hostname to be set. This has to be done before the udev rules are called!
 if [ -f "/etc/hostname" ]; then
-        /bin/hostname -b -F /etc/hostname 2>&1 1>/dev/null
+        /bin/hostname -F /etc/hostname >/dev/null 2>&1
 fi
 
 # Bring in the main config
@@ -76,41 +86,10 @@ for x in $(cat /proc/cmdline); do
 		;;
 	root=*)
 		ROOT=${x#root=}
-		case $ROOT in
-		LABEL=*)
-			ROOT="${ROOT#LABEL=}"
-
-			# support any / in LABEL= path (escape to \x2f)
-			case "${ROOT}" in
-			*/*)
-			if command -v sed >/dev/null 2>&1; then
-				ROOT="$(echo ${ROOT} | sed 's,/,\\x2f,g')"
-			else
-				if [ "${ROOT}" != "${ROOT#/}" ]; then
-					ROOT="\x2f${ROOT#/}"
-				fi
-				if [ "${ROOT}" != "${ROOT%/}" ]; then
-					ROOT="${ROOT%/}\x2f"
-				fi
-				IFS='/'
-				newroot=
-				for s in $ROOT; do
-					newroot="${newroot:+${newroot}\\x2f}${s}"
-				done
-				unset IFS
-				ROOT="${newroot}"
-			fi
-			esac
-			ROOT="/dev/disk/by-label/${ROOT}"
-			;;
-		UUID=*)
-			ROOT="/dev/disk/by-uuid/${ROOT#UUID=}"
-			;;
-		/dev/nfs)
-			[ -z "${BOOT}" ] && BOOT=nfs
-			;;
-		esac
-		;;
+		if [ -z "${BOOT}" ] && [ "$ROOT" = "/dev/nfs" ]; then
+			BOOT=nfs
+		fi
+                ;;
 	rootflags=*)
 		ROOTFLAGS="-o ${x#rootflags=}"
 		;;
@@ -149,6 +128,9 @@ for x in $(cat /proc/cmdline); do
 	ip=*)
 		IP="${x#ip=}"
 		;;
+	ip6=*)
+		IP6="${x#ip6=}"
+		;;
 	boot=*)
 		BOOT=${x#boot=}
 		;;
@@ -157,6 +139,10 @@ for x in $(cat /proc/cmdline); do
 		;;
 	resume=*)
 		RESUME="${x#resume=}"
+		case $RESUME in
+	        UUID=*)
+			RESUME="/dev/disk/by-uuid/${RESUME#UUID=}"
+		esac
 		;;
 	resume_offset=*)
 		resume_offset="${x#resume_offset=}"
@@ -164,16 +150,17 @@ for x in $(cat /proc/cmdline); do
 	noresume)
 		noresume=y
 		;;
+	drop_capabilities=*)
+		drop_caps="-d ${x#drop_capabilities=}"
+		;;
 	panic=*)
 		panic="${x#panic=}"
 		case ${panic} in
+		-1) ;;
 		*[![:digit:].]*)
 			panic=
 			;;
 		esac
-		;;
-	quiet)
-		quiet=y
 		;;
 	ro)
 		readonly=y
@@ -184,7 +171,11 @@ for x in $(cat /proc/cmdline); do
 	debug)
 		debug=y
 		quiet=n
-		exec >/run/initramfs/initramfs.debug 2>&1
+		if [ -n "${netconsole}" ]; then
+			exec >/dev/kmsg 2>&1
+		else
+			exec >/run/initramfs/initramfs.debug 2>&1
+		fi
 		set -x
 		;;
 	debug=*)
@@ -203,12 +194,25 @@ for x in $(cat /proc/cmdline); do
 		;;
 	netconsole=*)
 		netconsole=${x#netconsole=}
+		[ "x$debug" = "xy" ] && exec >/dev/kmsg 2>&1
 		;;
 	BOOTIF=*)
 		BOOTIF=${x#BOOTIF=}
 		;;
 	hwaddr=*)
-		BOOTIF=${x#BOOTIF=}
+		BOOTIF=${x#hwaddr=}
+		;;
+	fastboot|fsck.mode=skip)
+		fastboot=y
+		;;
+	forcefsck|fsck.mode=force)
+		forcefsck=y
+		;;
+	fsckfix|fsck.repair=yes)
+		fsckfix=y
+		;;
+	fsck.repair=no)
+		fsckfix=n
 		;;
 	recovery)
 		recovery=y
@@ -216,8 +220,13 @@ for x in $(cat /proc/cmdline); do
 	esac
 done
 
-if [ -n "${noresume}" ]; then
-	export noresume
+# Default to BOOT=local if no boot script defined.
+if [ -z "${BOOT}" ]; then
+	BOOT=local
+fi
+
+if [ -n "${noresume}" ] || [ "$RESUME" = none ]; then
+	export noresume=y
 	unset resume
 else
 	resume=${RESUME:-}
@@ -234,10 +243,9 @@ run_scripts /scripts/init-top
 
 maybe_break modules
 [ "$quiet" != "y" ] && log_begin_msg "Loading essential drivers"
+[ -n "${netconsole}" ] && modprobe netconsole netconsole="${netconsole}"
 load_modules
 [ "$quiet" != "y" ] && log_end_msg
-
-[ -n "${netconsole}" ] && modprobe netconsole netconsole="${netconsole}"
 
 maybe_break premount
 [ "$quiet" != "y" ] && log_begin_msg "Running /scripts/init-premount"
@@ -246,88 +254,63 @@ run_scripts /scripts/init-premount
 
 maybe_break mount
 log_begin_msg "Mounting root file system"
+# Always load local and nfs (since these might be needed for /etc or
+# /usr, irrespective of the boot script used to mount the rootfs).
+. /scripts/local
+. /scripts/nfs
 . /scripts/${BOOT}
 parse_numeric ${ROOT}
 maybe_break mountroot
+mount_top
+mount_premount
 mountroot
 log_end_msg
 
+if read_fstab_entry /usr; then
+	log_begin_msg "Mounting /usr file system"
+	mountfs /usr
+	log_end_msg
+fi
+
+# Mount cleanup
+mount_bottom
+nfs_bottom
+local_bottom
+
 maybe_break bottom
 [ "$quiet" != "y" ] && log_begin_msg "Running /scripts/init-bottom"
+# We expect udev's init-bottom script to move /dev to ${rootmnt}/dev
 run_scripts /scripts/init-bottom
 [ "$quiet" != "y" ] && log_end_msg
 
-# Preserve information on old systems without /run on the rootfs
-if [ -d ${rootmnt}/run ]; then
-	mount -n -o move /run ${rootmnt}/run
-else
-	# The initramfs udev database must be migrated:
-	if [ -d /run/udev ] && [ ! -d /dev/.udev ]; then
-		mv /run/udev /dev/.udev
-	fi
-	# The initramfs debug info must be migrated:
-	if [ -d /run/initramfs ] && [ ! -d /dev/.initramfs ]; then
-		mv /run/initramfs /dev/.initramfs
-	fi
-	umount /run
-fi
-
-# Move virtual filesystems over to the real filesystem
-mount -n -o move /sys ${rootmnt}/sys
-mount -n -o move /proc ${rootmnt}/proc
+# Move /run to the root
+mount -n -o move /run ${rootmnt}/run
 
 validate_init() {
-	checktarget="${1}"
-
-	# Work around absolute symlinks
-	if [ -d "${rootmnt}" ] && [ -h "${rootmnt}${checktarget}" ]; then
-		case $(readlink "${rootmnt}${checktarget}") in /*)
-			checktarget="$(chroot ${rootmnt} readlink ${checktarget})"
-			;;
-		esac
-	fi
-
-	# Make sure the specified init can be executed
-	if [ ! -x "${rootmnt}${checktarget}" ]; then
-		return 1
-	fi
-
-	# Upstart uses /etc/init as configuration directory :-/
-	if [ -d "${rootmnt}${checktarget}" ]; then
-		return 1
-	fi
+	run-init -n "${rootmnt}" "${1}"
 }
 
-# Check init bootarg
-if [ -n "${init}" ]; then
-	if ! validate_init "$init"; then
-		echo "Target filesystem doesn't have requested ${init}."
-		init=
-	fi
+# Check init is really there
+if ! validate_init "$init"; then
+	echo "Target filesystem doesn't have requested ${init}."
+	init=
+	for inittest in /sbin/init /etc/init /bin/init /bin/sh; do
+		if validate_init "${inittest}"; then
+			init="$inittest"
+			break
+		fi
+	done
 fi
 
-# Common case: /sbin/init is present
-if [ ! -x "${rootmnt}/sbin/init" ]; then
-	# ... if it's not available search for valid init
-	if [ -z "${init}" ] ; then
-		for inittest in /sbin/init /etc/init /bin/init /bin/sh; do
-			if validate_init "${inittest}"; then
-				init="$inittest"
-				break
-			fi
-		done
-	fi
-
-	# No init on rootmount
-	if ! validate_init "${init}" ; then
-		panic "No init found. Try passing init= bootarg."
-	fi
+# No init on rootmount
+if ! validate_init "${init}" ; then
+	panic "No init found. Try passing init= bootarg."
 fi
 
 maybe_break init
 
 # don't leak too much of env - some init(8) don't clear it
-# (keep init, rootmnt)
+# (keep init, rootmnt, drop_caps)
 unset debug
 unset MODPROBE_OPTIONS
 unset DPKG_ARCH
@@ -336,6 +319,7 @@ unset ROOTFSTYPE
 unset ROOTDELAY
 unset ROOT
 unset IP
+unset IP6
 unset BOOT
 unset BOOTIF
 unset UBIMTD
@@ -347,7 +331,15 @@ unset quiet
 unset readonly
 unset resume
 unset resume_offset
+unset fastboot
+unset forcefsck
+unset fsckfix
+
+# Move virtual filesystems over to the real filesystem
+mount -n -o move /sys ${rootmnt}/sys
+mount -n -o move /proc ${rootmnt}/proc
 
 # Chain to real filesystem
-exec run-init ${rootmnt} ${init} "$@" ${recovery:+--startup-event=recovery} <${rootmnt}/dev/console >${rootmnt}/dev/console 2>&1
-panic "Could not execute run-init."
+exec run-init ${drop_caps} ${rootmnt} ${init} "$@" ${recovery:+--startup-event=recovery} <${rootmnt}/dev/console >${rootmnt}/dev/console 2>&1
+echo "Something went badly wrong in the initramfs."
+panic "Please file a bug on initramfs-tools."
diff --git a/isosource/chroot/var/lib/dpkg/info/base-files.postinst b/isosource/chroot/var/lib/dpkg/info/base-files.postinst
--- a/isosource/chroot/var/lib/dpkg/info/base-files.postinst
+++ b/isosource/chroot/var/lib/dpkg/info/base-files.postinst
@@ -9,7 +9,7 @@ install_local_dir() {
 
 install_from_default() {
   if [ ! -f $2 ]; then
-    cp -p $1 $2
+    cp -p /usr/share/base-files/$1 $2
   fi
 }
 
@@ -28,6 +28,18 @@ migrate_directory() {
   fi
 }
 
+update_to_current_default() {
+  if [ -f $2 ]; then
+    md5=`md5sum $2 | cut -f 1 -d " "`
+    if grep -q "$md5" /usr/share/base-files/$1.md5sums; then
+      if ! cmp -s /usr/share/base-files/$1 $2; then
+        cp -p /usr/share/base-files/$1 $2
+        echo Updating $2 to current default.
+      fi
+    fi
+  fi
+}
+
 if [ ! -e /etc/dpkg/origins/default ]; then
   if [ -e /etc/dpkg/origins/ubuntu ]; then
     ln -sf ubuntu /etc/dpkg/origins/default
@@ -35,11 +47,11 @@ if [ ! -e /etc/dpkg/origins/default ]; then
 fi
 
 if [ "$1" = "configure" ] && [ "$2" = "" ]; then
-  install_from_default /usr/share/base-files/nsswitch.conf /etc/nsswitch.conf
-  install_from_default /usr/share/base-files/dot.profile   /root/.profile
-  install_from_default /usr/share/base-files/dot.bashrc    /root/.bashrc
-  install_from_default /usr/share/base-files/profile       /etc/profile
-  install_from_default /usr/share/base-files/networks      /etc/networks
+  install_from_default dot.profile   /root/.profile
+  install_from_default dot.bashrc    /root/.bashrc
+  install_from_default profile       /etc/profile
+  install_from_default networks      /etc/networks
+  install_directory mnt       755 root
   install_directory srv       755 root
   install_directory opt       755 root
   install_directory etc/opt   755 root
@@ -86,18 +98,15 @@ fi
 
 if [ ! -d /var/lib/dpkg ]; then
   mkdir -m 755 -p /var/lib/dpkg
-  chown root:root /var/lib/dpkg
 fi
 if [ ! -f /var/lib/dpkg/status ]; then
   echo > /var/lib/dpkg/status
   chmod 644 /var/lib/dpkg/status
-  chown root:root /var/lib/dpkg/status
 fi
 
 if [ ! -f /usr/info/dir ] && [ ! -f /usr/share/info/dir ]; then
-  install_from_default /usr/share/base-files/info.dir /usr/share/info/dir
+  install_from_default info.dir /usr/share/info/dir
   chmod 644 /usr/share/info/dir
-  chown root:root /usr/share/info/dir
 fi
 
 if [ "$1" = "configure" ] && [ "$2" != "" ]; then
@@ -109,14 +118,47 @@ if [ "$1" = "configure" ] && [ "$2" != "" ]; then
     /usr/lib/update-manager/check-new-release -q > /var/lib/update-notifier/release-upgrade-available  &
   fi
 
-  if [ -f /etc/profile ]; then
-    md5=`md5sum /etc/profile | cut -f 1 -d " "`
-    if grep -q "$md5" /usr/share/base-files/profile.md5sums; then
-      if ! cmp -s /usr/share/base-files/profile /etc/profile; then
-        cp -p /usr/share/base-files/profile /etc/profile
-        echo Updating /etc/profile to current default.
-      fi
-    fi
+  update_to_current_default profile       /etc/profile
+  update_to_current_default dot.profile   /root/.profile
+  if dpkg --compare-versions "$2" lt-nl "7.7"; then
+    install_directory mnt 755 root
   fi
 fi
+
+# Automatically added by dh_systemd_enable/11.1.6ubuntu1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'motd-news.timer' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'motd-news.timer'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'motd-news.timer' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'motd-news.timer' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_systemd_start/11.1.6ubuntu1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		deb-systemd-invoke start 'motd-news.timer' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_systemd_start/11.1.6ubuntu1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		deb-systemd-invoke start 'motd-news.service' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installdeb/11.1.6ubuntu1
+dpkg-maintscript-helper rm_conffile /etc/update-motd.d/50-news 9.6ubuntu11~ -- "$@"
+# End automatically added section
 
diff --git a/isosource/chroot/var/lib/dpkg/info/kmod.postinst b/isosource/chroot/var/lib/dpkg/info/kmod.postinst
--- a/isosource/chroot/var/lib/dpkg/info/kmod.postinst
+++ b/isosource/chroot/var/lib/dpkg/info/kmod.postinst
@@ -65,9 +65,16 @@ case "$1" in
   fi
 esac
 
-# Automatically added by dh_installinit
-if [ -x "/etc/init.d/kmod" ]; then
-	update-rc.d kmod defaults >/dev/null
+dpkg-maintscript-helper rm_conffile /etc/modprobe.d/mlx4.conf 24-1ubuntu2 kmod -- "$@"
+
+# Automatically added by dh_installdeb/11.1.6ubuntu2
+dpkg-maintscript-helper rm_conffile /etc/init/kmod.conf 24-1ubuntu2~ kmod -- "$@"
+# End automatically added section
+# Automatically added by dh_installinit/11.1.6ubuntu2
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "/etc/init.d/kmod" ]; then
+		update-rc.d kmod defaults >/dev/null || exit 1
+	fi
 fi
 # End automatically added section
 
diff --git a/isosource/chroot/var/lib/dpkg/info/passwd.postinst b/isosource/chroot/var/lib/dpkg/info/passwd.postinst
--- a/isosource/chroot/var/lib/dpkg/info/passwd.postinst
+++ b/isosource/chroot/var/lib/dpkg/info/passwd.postinst
@@ -1,4 +1,6 @@
-#!/bin/sh -e
+#!/bin/sh
+
+set -e
 
 case "$1" in
 configure)
@@ -37,6 +39,18 @@ esac
 # Run shadowconfig only on new installs
 [ -z "$2" ] && shadowconfig on
 
+# Automatically added by dh_installinit/11.1.3ubuntu1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# In case this system is running systemd, we need to ensure that all
+	# necessary tmpfiles (if any) are created before starting.
+	if [ -d /run/systemd/system ] ; then
+		systemd-tmpfiles --create /usr/lib/tmpfiles.d/passwd.conf >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installdeb/11.1.3ubuntu1
+dpkg-maintscript-helper rm_conffile /etc/init/passwd.conf 1:4.2-3.2ubuntu4\~ passwd -- "$@"
+# End automatically added section
 
 
 exit 0
diff --git a/isosource/chroot/var/lib/dpkg/info/systemd.postinst b/isosource/chroot/var/lib/dpkg/info/systemd.postinst
--- a/isosource/chroot/var/lib/dpkg/info/systemd.postinst
+++ b/isosource/chroot/var/lib/dpkg/info/systemd.postinst
@@ -21,17 +21,15 @@ if [ "$1" = "triggered" ]; then
                 _update_catalog
                 ;;
             /etc/init.d)
-                _systemctl daemon-reload
+                _systemctl daemon-reload || true
                 ;;
         esac
     done
     exit 0
 fi
 
-# Enable getty and remote-fs.target by default on new installs, and on
-# upgrades from old systemd versions (where the symlinks included as deb
-# content, and will thus have been removed by dpkg during the upgrade).
-if dpkg --compare-versions "$2" lt "214-1"; then
+# Enable getty and remote-fs.target by default on new installs
+if [ -z "$2" ]; then
     systemctl enable getty@tty1.service || true
     systemctl enable remote-fs.target || true
 fi
@@ -41,31 +39,49 @@ if dpkg --compare-versions "$2" lt "218-11~"; then
     systemctl enable systemd-timesyncd.service || true
 fi
 
-# Cleanup state files from the auto-enabler which we used in wheezy
-if dpkg --compare-versions "$2" lt "204-1"; then
-    rm -f /var/lib/systemd/enabled-units
-    rm -f /var/lib/systemd/run-debian-enable-units
-    rm -f /var/lib/systemd/*.symlinks
+# Enable resolved by default on new installs installs and upgrades
+if dpkg --compare-versions "$2" lt "234-1ubuntu2~"; then
+    systemctl enable systemd-resolved.service || true
+fi
+
+# Drop stock /etc/rc.local on upgrades
+if dpkg --compare-versions "$2" lt "234-2ubuntu11~"; then
+        if [ -f /etc/rc.local ]; then
+                if [ "10fd9f051accb6fd1f753f2d48371890" = "$(md5sum /etc/rc.local | cut -d\  -f1)" ]; then
+                        echo Removing empty /etc/rc.local
+                        rm -f /etc/rc.local || true
+                fi
+        fi
+fi
+
+# Use stub resolve.conf by default on new installs
+if [ -z "$2" ]; then
+    mkdir -p /run/systemd/resolve
+    if [ -e /etc/resolv.conf ]; then
+            cp /etc/resolv.conf /run/systemd/resolve/stub-resolv.conf
+    fi
+    # If /etc/resolv.conf is a bind-mount, moving or replacing
+    # /etc/resolv.conf may fail
+    ln -snf ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf || true
+fi
+
+# Enable ondemand by default on new installs installs and upgrades
+if [ -e /lib/systemd/system/ondemand.service ] && dpkg --compare-versions "$2" lt "231-7~"; then
+    systemctl enable ondemand.service || true
 fi
 
 # Do a one-time migration of the local time setting
-if dpkg --compare-versions "$2" lt "33-1"; then
+if [ -z "$2" ]; then
     if [ -f /etc/default/rcS ]; then
         . /etc/default/rcS
     fi
     if [ "$UTC" = "no" ] && [ ! -e /etc/adjtime ]; then
-        printf "0.0 0 0.0\n0\nLOCAL" > /etc/adjtime
+        printf "0.0 0 0.0\n0\nLOCAL\n" > /etc/adjtime
     fi
 fi
 
 # Do a one-time migration of the TMPTIME setting
-if dpkg --compare-versions "$2" lt "204-9"; then
-    # Fix up potentially broken tmp.conf, see Debian#738862
-    if [ -e /etc/tmpfiles.d/tmp.conf ]; then
-        sed -i '/^# Clear \/var\/tmp/d' /etc/tmpfiles.d/tmp.conf
-        sed -i 's,^\(d /var/tmp\),#\1,g' /etc/tmpfiles.d/tmp.conf
-    fi
-
+if [ -z "$2" ]; then
     if [ -f /etc/default/rcS ]; then
         . /etc/default/rcS
     fi
@@ -84,7 +100,7 @@ EOF
 fi
 
 # Do a one-time migration of the RAMTMP setting
-if dpkg --compare-versions "$2" lt "204-8"; then
+if [ -z "$2" ]; then
     if [ -f /etc/default/rcS ]; then
         . /etc/default/rcS
     fi
@@ -93,16 +109,10 @@ if dpkg --compare-versions "$2" lt "204-8"; then
     fi
     if [ "$RAMTMP" = "yes" ]; then
         # systemctl enable will work even when systemd is not the active PID 1.
-        systemctl enable tmp.mount || true
-    fi
-fi
-
-if dpkg --compare-versions "$2" lt "40-1"; then
-    # /lib/init/rw has been replaced by /run, so try to remove it on upgrades
-    # http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=643699
-    _systemctl stop lib-init-rw.automount lib-init-rw.mount || true
-    if [ -d /lib/init/rw ]; then
-        rmdir --ignore-fail-on-non-empty /lib/init/rw || true
+        if [ ! -e /etc/systemd/system/tmp.mount ]; then
+            cp /usr/share/systemd/tmp.mount /etc/systemd/system/tmp.mount
+            systemctl enable tmp.mount || true
+        fi
     fi
 fi
 
@@ -111,85 +121,78 @@ systemd-machine-id-setup
 
 # Setup system users and groups
 addgroup --quiet --system systemd-journal
-addgroup --quiet --system systemd-journal-remote
 
-adduser --quiet --system --group --no-create-home --home /run/systemd \
-    --gecos "systemd Time Synchronization" systemd-timesync
+# Enable persistent journal, in auto-mode, by default on new installs installs and upgrades
+if dpkg --compare-versions "$2" lt "235-3ubuntu3~"; then
+    mkdir -p /var/log/journal
+    # create tmpfiles only when running systemd, otherwise %b substitution fails
+    if [ -d /run/systemd/system ]; then
+        systemd-tmpfiles --create --prefix /var/log/journal
+    fi
+fi
+
 adduser --quiet --system --group --no-create-home --home /run/systemd/netif \
     --gecos "systemd Network Management" systemd-network
 adduser --quiet --system --group --no-create-home --home /run/systemd/resolve \
     --gecos "systemd Resolver" systemd-resolve
-adduser --quiet --system --group --no-create-home --home /run/systemd \
-    --gecos "systemd Bus Proxy" systemd-bus-proxy
 
 # Initial update of the Message Catalogs database
 _update_catalog
 
-# Make systemd-detect-virt utility usable for non-root users
-setcap cap_dac_override,cap_sys_ptrace=ep /usr/bin/systemd-detect-virt || true
-
-# Re-run systemctl enable for any service that was enabled when preinst was run.
-if dpkg --compare-versions "$2" ge "204"; then
-    while read UNIT ; do
-        systemctl enable $UNIT || true
-    done </run/systemd/was-enabled || true
+# Disable networkd when upgrading from broken versions 8..10. Turns out
+# enabling networkd unconditionally has long boot time side-effects
+if dpkg --compare-versions "$2" gt "234-2ubuntu8~" &&
+   dpkg --compare-versions "$2" lt "234-2ubuntu11~"; then
+    systemctl disable systemd-networkd-wait-online.service || true
 fi
 
-if [ -n "$2" ]; then
+# skip daemon-reexec and try-restarts during shutdown to avoid hitting LP: #1803391
+if [ -n "$2" ] && [ "$(systemctl is-system-running)" != "stopping" ]; then
     _systemctl daemon-reexec || true
-    _systemctl try-restart systemd-logind.service || true
+    # don't restart logind; this can be done again once this gets implemented:
+    # https://github.com/systemd/systemd/issues/1163
     _systemctl try-restart systemd-networkd.service || true
     _systemctl try-restart systemd-resolved.service || true
     _systemctl try-restart systemd-timesyncd.service || true
-fi
-
-# The /dev/log socket and /dev/initctl FIFO have been moved to /run and
-# replaced by symlinks. Create the symlinks manually on upgrades as well.
-# (https://bugs.debian.org/761340). Note that this will break the current
-# journal as we cannot restart it properly (https://bugs.debian.org/771122) so
-# this is mostly an one-time upgrade path from wheezy.
-if dpkg --compare-versions "$2" lt-nl "215-3"; then
-    if [ -p /run/systemd/initctl/fifo ] && [ ! -L /dev/initctl ]; then
-         ln -sf /run/systemd/initctl/fifo /dev/initctl
-    fi
-    if [ -S /run/systemd/journal/dev-log ] && [ ! -L /dev/log ]; then
-         ln -sf /run/systemd/journal/dev-log /dev/log
-    fi
     _systemctl try-restart systemd-journald.service || true
 fi
 
-# In experimental we had created duplicate ACLs on /var/log/journal for a while
-# (https://bugs.debian.org/778656). Clean up after that.
-if dpkg --compare-versions "$2" lt-nl "219-4" && \
-    [ -d /var/log/journal ] && type setfacl >/dev/null 2>&1; then
-    echo "Cleaning up duplicate ACLs on /var/log/journal"
-    if setfacl -Rb /var/log/journal/; then
-        systemd-tmpfiles --create /usr/lib/tmpfiles.d/systemd.conf || true
-    fi
+# Cleanup hwclock-save.service, which was shipped in jessie.
+if dpkg --compare-versions "$2" lt-nl "228-5~"; then
+   for t in reboot halt poweroff ; do
+       rm -f /etc/systemd/system/${t}.target.wants/hwclock-save.service
+       rmdir --ignore-fail-on-non-empty /etc/systemd/system/${t}.target.wants 2> /dev/null || true
+   done
 fi
 
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/lsb-base-logging.sh 25-1~ systemd -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/tmpfiles.d/legacy.conf 29-1~ systemd -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/tmpfiles.d/systemd.conf 29-1~ systemd -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/tmpfiles.d/x11.conf 29-1~ systemd -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/systemctl-bash-completion.sh 204-1~ systemd -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/systemd-bash-completion.sh 204-1~ systemd -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper mv_conffile /etc/systemd/systemd-logind.conf /etc/systemd/logind.conf 204-1~ systemd -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper mv_conffile /etc/systemd/systemd-journald.conf /etc/systemd/journald.conf 204-1~ systemd -- "$@"
+if dpkg --compare-versions "$2" lt-nl "235-3~"; then
+    # systemd-bus-proxyd got dropped before stretch, and never created any file
+    deluser --system systemd-bus-proxy || true
+fi
+
+if dpkg --compare-versions "$2" lt-nl "236-1~"; then
+    # Clean up old /var/lib/systemd/clock on upgrade.
+    # The clock file used by systemd-timesyncd is now stored in
+    # StateDirectory=systemd/timesync.
+    rm -f /var/lib/systemd/clock
+fi
+
+# Process all tmpfiles that we ship, including any overrides in
+# runtime-dir/sysadmin-dir/other packages (e.g. rsyslog)
+#
+# Ignore if this fails, because e.g. %b will fail on WSL
+systemd-tmpfiles --create || :
+
+# Automatically added by dh_installdeb/11.1.6ubuntu2
+dpkg-maintscript-helper rm_conffile /etc/X11/xinit/xinitrc.d/50-systemd-user.sh 228-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/systemd/bootchart.conf 230-1\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.hostname1.conf 233-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.locale1.conf 233-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.login1.conf 233-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.machine1.conf 228-5\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.network1.conf 233-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.resolve1.conf 233-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.systemd1.conf 233-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.timedate1.conf 233-3\~ -- "$@"
 # End automatically added section
 
diff --git a/isosource/chroot/var/lib/dpkg/info/util-linux.postinst b/isosource/chroot/var/lib/dpkg/info/util-linux.postinst
--- a/isosource/chroot/var/lib/dpkg/info/util-linux.postinst
+++ b/isosource/chroot/var/lib/dpkg/info/util-linux.postinst
@@ -4,37 +4,72 @@ set -e
 update-alternatives --install /usr/bin/pager pager /bin/more 50 \
 	--slave /usr/share/man/man1/pager.1.gz pager.1.gz \
 	/usr/share/man/man1/more.1.gz
-update-alternatives --install /usr/bin/pager pager /usr/bin/pg 10 \
-	--slave /usr/share/man/man1/pager.1.gz pager.1.gz \
-	/usr/share/man/man1/pg.1.gz
 
-# hwclock works on all Linux architectures, except s390 (and s390x, of course).
-if [ "$(uname -s)" = "Linux" ]; then
-	model=$(uname -m)
-	if [ ${model%x} != "s390" ]; then
-		update-rc.d -f hwclock.sh remove >/dev/null 2>&1 || true
-		update-rc.d hwclock.sh defaults > /dev/null
+# We stopped shipping the 'pg' utility, so remove it as a pager
+# alternative on upgrades from Stretch.
+update-alternatives --remove pager /usr/bin/pg
+
+# Automatically added by dh_installdeb/11.1.4ubuntu1
+dpkg-maintscript-helper rm_conffile /etc/init/hwclock-save.conf 2.28.1-1ubuntu1\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/init/hwclock.conf 2.28.1-1ubuntu1\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/init/hwclock.sh.conf 2.28.1-1ubuntu1\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/cron.weekly/fstrim 2.31.1-0.4ubuntu1\~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installsystemd/11.1.4ubuntu1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'fstrim.timer' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'fstrim.timer'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'fstrim.timer' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'fstrim.timer' >/dev/null || true
 	fi
 fi
-
-if [ -L /usr/doc/util-linux ]; then
-	rm -f /usr/doc/util-linux
-fi
-
-# (hwclock-related) parts of this package are being pulled into initramfs,
-# so trigger an update of the initramfs.
-if [ -x /usr/sbin/update-initramfs ]; then
-	/usr/sbin/update-initramfs -u
-fi
-
-# Automatically added by dh_installinit
-if [ -x "/etc/init.d/hwclock-save" ]; then
-	update-rc.d hwclock-save defaults >/dev/null
+# End automatically added section
+# Automatically added by dh_installsystemd/11.1.4ubuntu1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+		if [ -d /run/systemd/system ]; then
+			systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		deb-systemd-invoke $_dh_action 'fstrim.timer' >/dev/null || true
+	fi
 fi
 # End automatically added section
-# Automatically added by dh_installinit
-if [ -x "/etc/init.d/hwclock" ]; then
-	update-rc.d hwclock defaults >/dev/null
+# Automatically added by dh_installsystemd/11.1.4ubuntu1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if deb-systemd-helper debian-installed 'fstrim.timer'; then
+		# This will only remove masks created by d-s-h on package removal.
+		deb-systemd-helper unmask 'fstrim.timer' >/dev/null || true
+
+		if deb-systemd-helper --quiet was-enabled 'fstrim.timer'; then
+			# Create new symlinks, if any.
+			deb-systemd-helper enable 'fstrim.timer' >/dev/null || true
+		fi
+	fi
+
+	# Update the statefile to add new symlinks (if any), which need to be cleaned
+	# up on purge. Also remove old symlinks.
+	deb-systemd-helper update-state 'fstrim.timer' >/dev/null || true
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/11.1.4ubuntu1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			deb-systemd-invoke try-restart 'fstrim.service' 'fstrim.timer' >/dev/null || true
+		fi
+	fi
 fi
 # End automatically added section
 
diff --git a/isosource/chroot/var/lib/dpkg/info/uuid-runtime.postinst b/isosource/chroot/var/lib/dpkg/info/uuid-runtime.postinst
--- a/isosource/chroot/var/lib/dpkg/info/uuid-runtime.postinst
+++ b/isosource/chroot/var/lib/dpkg/info/uuid-runtime.postinst
@@ -1,22 +1,6 @@
 #!/bin/sh
 set -e
 
-# upgrade existing libuuid user/group.
-if getent group libuuid >/dev/null && ! getent group uuidd >/dev/null ; then
-	groupmod --new-name uuidd libuuid
-fi
-if getent passwd libuuid >/dev/null && ! getent passwd uuidd >/dev/null ; then
-	# attempt to stop potentially running uuidd, otherwise usermod will fail.
-	invoke-rc.d --quiet uuidd stop || true
-
-	# rename user, change shell and set new homedir.
-	usermod --login uuidd --shell /bin/false --home /run/uuidd libuuid
-
-	# attemp cleanup of old home directory.
-	[ -d /var/lib/libuuid ] && \
-		rmdir --ignore-fail-on-non-empty /var/lib/libuuid
-fi
-
 # add uuidd user/group if needed.
 if ! getent group uuidd >/dev/null; then
 	addgroup --system uuidd
@@ -27,47 +11,51 @@ if ! getent passwd uuidd >/dev/null; then
 		uuidd
 fi
 
-# Automatically added by dh_systemd_enable
-# This will only remove masks created by d-s-h on package removal.
-deb-systemd-helper unmask uuidd.service >/dev/null || true
-
-# was-enabled defaults to true, so new installations run enable.
-if deb-systemd-helper --quiet was-enabled uuidd.service; then
-	# Enables the unit on first installation, creates new
-	# symlinks on upgrades if the unit file has changed.
-	deb-systemd-helper enable uuidd.service >/dev/null || true
-else
-	# Update the statefile to add new symlinks (if any), which need to be
-	# cleaned up on purge. Also remove old symlinks.
-	deb-systemd-helper update-state uuidd.service >/dev/null || true
-fi
-# End automatically added section
-# Automatically added by dh_systemd_enable
-# This will only remove masks created by d-s-h on package removal.
-deb-systemd-helper unmask uuidd.socket >/dev/null || true
-
-# was-enabled defaults to true, so new installations run enable.
-if deb-systemd-helper --quiet was-enabled uuidd.socket; then
-	# Enables the unit on first installation, creates new
-	# symlinks on upgrades if the unit file has changed.
-	deb-systemd-helper enable uuidd.socket >/dev/null || true
-else
-	# Update the statefile to add new symlinks (if any), which need to be
-	# cleaned up on purge. Also remove old symlinks.
-	deb-systemd-helper update-state uuidd.socket >/dev/null || true
-fi
-# End automatically added section
-# Automatically added by dh_installinit
-if [ -x "/etc/init.d/uuidd" ]; then
-	update-rc.d uuidd defaults >/dev/null   
-fi
-if [ -x "/etc/init.d/uuidd" ] || [ -e "/etc/init/uuidd.conf" ]; then
-	if [ -n "$2" ]; then
-		_dh_action=restart
-	else
-		_dh_action=start
+# Automatically added by dh_installinit/11.1.6ubuntu2
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "/etc/init.d/uuidd" ]; then
+		update-rc.d uuidd defaults >/dev/null
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		invoke-rc.d uuidd $_dh_action || exit 1
 	fi
-	invoke-rc.d uuidd $_dh_action || exit $?
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/11.1.6ubuntu2
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'uuidd.service' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'uuidd.service'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'uuidd.service' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'uuidd.service' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/11.1.6ubuntu2
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'uuidd.socket' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'uuidd.socket'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'uuidd.socket' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'uuidd.socket' >/dev/null || true
+	fi
 fi
 # End automatically added section
 
